    export const colors = {
        fontSize: '16px',

        // TCG Theme Colors - Dark Teal & Gold
        background: '#0a1f2e',
        foreground: '#e8eef2',
        card: '#132838',
        cardForeground: '#e8eef2',
        popover: '#132838',
        popoverForeground: '#e8eef2',
        primary: '#d4af37',
        primaryForeground: '#0a1f2e',
        secondary: '#1e3a4a',
        secondaryForeground: '#e8eef2',
        muted: '#1e3a4a',
        mutedForeground: '#8fa3b0',
        accent: '#2a4a5c',
        accentForeground: '#e8eef2',
        destructive: '#d4183d',
        destructiveForeground: '#ffffff',
        border: 'rgba(212, 175, 55, 0.2)',
        input: 'rgba(212, 175, 55, 0.2)',
        inputBackground: '#1e3a4a',
        switchBackground: '#2a4a5c',
        fontWeightMedium: 500,
        fontWeightNormal: 400,
        ring: '#d4af37',

        // TCG Accent Colors
        gold: '#d4af37',
        goldLight: '#f0d574',
        goldDark: '#b8941f',
        teal: '#0a1f2e',
        tealLight: '#1e3a4a',
        tealLighter: '#2a4a5c',
        purple: '#8b5cf6',
        purpleLight: '#a78bfa',

        chart1: '#d4af37',
        chart2: '#8b5cf6',
        chart3: '#3b82f6',
        chart4: '#10b981',
        chart5: '#f59e0b',

        radius: '0.75rem',
        radiusSm: 'calc(0.75rem - 4px)',
        radiusMd: 'calc(0.75rem - 2px)',
        radiusLg: '0.75rem',
        radiusXl: 'calc(0.75rem + 4px)',

        sidebar: '#132838',
        sidebarForeground: '#e8eef2',
        sidebarPrimary: '#d4af37',
        sidebarPrimaryForeground: '#0a1f2e',
        sidebarAccent: '#1e3a4a',
        sidebarAccentForeground: '#e8eef2',
        sidebarBorder: 'rgba(212, 175, 55, 0.2)',
        sidebarRing: '#d4af37',

        // color-* aliases (resolved)
        colorBackground: '#0a1f2e',
        colorForeground: '#e8eef2',
        colorCard: '#132838',
        colorCardForeground: '#e8eef2',
        colorPopover: '#132838',
        colorPopoverForeground: '#e8eef2',
        colorPrimary: '#d4af37',
        colorPrimaryForeground: '#0a1f2e',
        colorSecondary: '#1e3a4a',
        colorSecondaryForeground: '#e8eef2',
        colorMuted: '#1e3a4a',
        colorMutedForeground: '#8fa3b0',
        colorAccent: '#2a4a5c',
        colorAccentForeground: '#e8eef2',
        colorDestructive: '#d4183d',
        colorDestructiveForeground: '#ffffff',
        colorBorder: 'rgba(212, 175, 55, 0.2)',
        colorInput: 'rgba(212, 175, 55, 0.2)',
        colorInputBackground: '#1e3a4a',
        colorSwitchBackground: '#2a4a5c',
        colorRing: '#d4af37',
        colorChart1: '#d4af37',
        colorChart2: '#8b5cf6',
        colorChart3: '#3b82f6',
        colorChart4: '#10b981',
        colorChart5: '#f59e0b',
        colorSidebar: '#132838',
        colorSidebarForeground: '#e8eef2',
        colorSidebarPrimary: '#d4af37',
        colorSidebarPrimaryForeground: '#0a1f2e',
        colorSidebarAccent: '#1e3a4a',
        colorSidebarAccentForeground: '#e8eef2',
        colorSidebarBorder: 'rgba(212, 175, 55, 0.2)',
        colorSidebarRing: '#d4af37',

        // Custom TCG colors aliases
        colorGold: '#d4af37',
        colorGoldLight: '#f0d574',
        colorGoldDark: '#b8941f',
        colorTeal: '#0a1f2e',
        colorTealLight: '#1e3a4a',
        colorTealLighter: '#2a4a5c',
        colorPurple: '#8b5cf6',
        colorPurpleLight: '#a78bfa',
    } as const;